# Generated by Django 6.0.7 on 2026-07-27 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('procurement', '0002_purchaserequest_tier3_approver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='budget_line',
            field=models.ForeignKey(blank=True, help_text='Which budget line this request draws from. Optional — required only if you want approval to auto-create a committed CostTransaction (see apps.integrations).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='budget.budgetline'),
        ),
    ]
