# Generated by Django 6.0.7 on 2026-08-05 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_pendingstockitemrequest'),
        ('procurement', '0003_purchaserequest_budget_line'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestitem',
            name='approved_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What was actually authorized — may differ from quantity requested.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='delivered_by',
            field=models.CharField(blank=True, help_text='Free text — supplier driver name, or "Company driver", etc.', max_length=255),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='delivered_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="What the supplier's delivery note says arrived.", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='received_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What was actually counted in on receipt — may differ from delivered_quantity.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='stock_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_pr_items', to='inventory.stockmovement'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='tier2_decision',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated to Director')], max_length=10),
        ),
    ]
