# Generated by Django 6.0.7 on 2026-08-13 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_purchaserequestitem_approved_quantity_and_more'),
        ('suppliers', '0002_rename_address_supplier_physical_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, help_text='Auto-generated, e.g. LPO-0001.', max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.CharField(blank=True, max_length=255)),
                ('company_po_box', models.CharField(blank=True, max_length=100)),
                ('company_phone', models.CharField(blank=True, max_length=32)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_address', models.CharField(blank=True, max_length=255)),
                ('supplier_email', models.EmailField(blank=True, max_length=254)),
                ('supplier_phone', models.CharField(blank=True, max_length=32)),
                ('vat_applicable', models.BooleanField(default=True)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=16, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('awaiting_signature', 'Awaiting Signature'), ('signed', 'Signed'), ('sent', 'Sent to Supplier'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='awaiting_signature', max_length=20)),
                ('signature_mode', models.CharField(blank=True, choices=[('wet_ink', 'Wet-ink signature (scanned copy uploaded)'), ('digital', 'Digital approval')], max_length=10)),
                ('signed_document', models.FileField(blank=True, null=True, upload_to='lpo_signed/%Y/%m/')),
                ('digitally_approved_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_location', models.CharField(blank=True, choices=[('site', 'Project Site'), ('main_warehouse', 'Main Warehouse')], max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('digitally_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lpo', to='procurement.purchaserequest')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lpos', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LPOItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.lpo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
