# Generated by Django 6.0.7 on 2026-08-18 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_lpo_lpoitem'),
        ('projects', '0001_initial'),
        ('suppliers', '0002_rename_address_supplier_physical_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lpo',
            name='origin',
            field=models.CharField(choices=[('generated', 'Generated in System'), ('manual', 'Manually Recorded')], default='generated', max_length=10),
        ),
        migrations.AddField(
            model_name='lpo',
            name='project',
            field=models.ForeignKey(default=1, help_text='Which project this LPO is for — taken from purchase_request.project when generated, or set directly when recorded manually. Drives per-project spend tracking regardless of how the LPO was created.', on_delete=django.db.models.deletion.PROTECT, related_name='lpos', to='projects.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lpo',
            name='source_document',
            field=models.FileField(blank=True, help_text='For manually-recorded LPOs: the original document (e.g. a photographed handwritten order, or a copy of an externally-issued LPO) — the record of what was actually agreed. The structured fields alongside it are typed in by hand so this LPO works identically to a generated one everywhere else in the system.', null=True, upload_to='lpo_source/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='lpo',
            name='purchase_request',
            field=models.OneToOneField(blank=True, help_text='Set for system-generated LPOs, and optionally for manually-recorded ones that fulfil an existing request (e.g. one escalated from a restock shortfall). Null for a manual LPO with no PR behind it.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lpo', to='procurement.purchaserequest'),
        ),
        migrations.CreateModel(
            name='SupplierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('description_key', models.CharField(editable=False, max_length=255)),
                ('times_ordered', models.PositiveIntegerField(default=0)),
                ('last_ordered_at', models.DateTimeField(blank=True, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_items', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-times_ordered'],
                'unique_together': {('supplier', 'description_key')},
            },
        ),
    ]
