# Generated by Django 6.0.7 on 2026-07-21 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_company_procurement_approval_threshold'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, help_text='Auto-generated, e.g. ITM-0001.', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('materials', 'Building Materials'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('tools', 'Tools'), ('safety', 'Safety Equipment'), ('other', 'Other')], default='materials', max_length=20)),
                ('unit', models.CharField(help_text='e.g. bags, tons, pieces, meters.', max_length=30)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, help_text='Alert when total stock falls at or below this level.', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('main', 'Main Warehouse'), ('project', 'Project Store')], max_length=10)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
                ('project', models.OneToOneField(blank=True, help_text='Set only for project stores; null for the Main Warehouse.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='projects.project')),
            ],
            options={
                'ordering': ['location_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('receipt', 'Goods Received'), ('issue', 'Issued Out'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('adjustment', 'Stock Adjustment')], max_length=15)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, help_text='e.g. a Purchase Request code or delivery note number.', max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockitem')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('related_warehouse', models.ForeignKey(blank=True, help_text='For transfers: the other warehouse involved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_movements', to='inventory.warehouse')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='inventory.stockitem')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='inventory.warehouse')),
            ],
            options={
                'unique_together': {('warehouse', 'item')},
            },
        ),
    ]
