# Generated by Django 6.0.7 on 2026-07-27 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('inventory', '0002_stockmovement_paired_movement_stockmovement_reverses'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='standard_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Reference unit cost, used as a fallback when a StockMovement doesn't specify its own unit_cost.", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='budget_line',
            field=models.ForeignKey(blank=True, help_text="Which budget line this movement's cost applies to. Only used for movement_type='issue' — see apps.integrations.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='budget.budgetline'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Cost per unit for THIS movement. Falls back to item.standard_cost if not set. Only meaningful for movement_type='issue'.", max_digits=12, null=True),
        ),
    ]
