# Generated by Django 6.0.7 on 2026-08-04 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_procurement_approval_threshold'),
        ('inventory', '0003_stockitem_standard_cost_stockmovement_budget_line_and_more'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingStockItemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_name', models.CharField(max_length=255)),
                ('suggested_unit', models.CharField(blank=True, max_length=30)),
                ('suggested_category', models.CharField(choices=[('materials', 'Building Materials'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('tools', 'Tools'), ('safety', 'Safety Equipment'), ('other', 'Other')], default='other', max_length=20)),
                ('quantity_requested', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
                ('project', models.ForeignKey(blank=True, help_text='The project this was requested from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_stock_requests', to='projects.project')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_item_requests', to=settings.AUTH_USER_MODEL)),
                ('resolved_item', models.ForeignKey(blank=True, help_text='Set once approved — the real catalog item this request became.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_from_requests', to='inventory.stockitem')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
