# Generated by Django 6.0.7 on 2026-08-09 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_procurement_approval_threshold'),
        ('inventory', '0004_pendingstockitemrequest'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRestockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_requested', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.CharField(blank=True, help_text='Optional context from the requester, e.g. "need by Friday".', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
                ('item', models.ForeignKey(help_text='Must already exist in the catalog — this is not for new items.', on_delete=django.db.models.deletion.PROTECT, related_name='restock_requests', to='inventory.stockitem')),
                ('project', models.ForeignKey(help_text='The project whose store needs restocking.', on_delete=django.db.models.deletion.CASCADE, related_name='restock_requests', to='projects.project')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restock_requests', to=settings.AUTH_USER_MODEL)),
                ('resulting_movement', models.OneToOneField(blank=True, help_text='The transfer_out movement created when this was approved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restock_request', to='inventory.stockmovement')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_warehouse', models.ForeignKey(blank=True, help_text='Where the stock should come from. Left blank to let the approver decide (defaults to Main Warehouse in that case).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_restock_requests', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
