# Generated by Django 6.0.7 on 2026-08-10 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockrestockrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrestockrequest',
            name='dispatch_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stockrestockrequest',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockrestockrequest',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockrestockrequest',
            name='receipt_movement',
            field=models.OneToOneField(blank=True, help_text='The transfer_in movement created on receipt.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restock_request_receipt', to='inventory.stockmovement'),
        ),
        migrations.AddField(
            model_name='stockrestockrequest',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockrestockrequest',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockrestockrequest',
            name='resulting_movement',
            field=models.OneToOneField(blank=True, help_text='The transfer_out movement created on dispatch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restock_request', to='inventory.stockmovement'),
        ),
        migrations.AlterField(
            model_name='stockrestockrequest',
            name='source_warehouse',
            field=models.ForeignKey(blank=True, help_text='Where the stock should come from. Left blank to let the dispatcher decide (defaults to Main Warehouse in that case).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_restock_requests', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='stockrestockrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('received', 'Received'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
