# Generated by Django 6.0.7 on 2026-08-18 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stockrestockrequest_dispatch_notes_and_more'),
        ('procurement', '0005_lpo_lpoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrestockrequest',
            name='fulfilled_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What was actually dispatched from source_warehouse. Null until dispatch happens. May be less than quantity_requested if the source warehouse could not fully cover it — the gap is the shortfall that can be escalated to Procurement.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='stockrestockrequest',
            name='generated_purchase_request',
            field=models.ForeignKey(blank=True, help_text="Set if the shortfall on this request was escalated to Procurement — the resulting PurchaseRequest, carrying this request's item and shortfall quantity forward without re-entry.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_restock_requests', to='procurement.purchaserequest'),
        ),
        migrations.AlterField(
            model_name='stockrestockrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partially_dispatched', 'Partially Dispatched — Shortfall Pending'), ('in_transit', 'In Transit'), ('received', 'Received'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
    ]
