# Generated by Django 6.0.7 on 2026-07-19 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('actor', models.ForeignKey(help_text='Who performed the action. Null if the user was later deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, help_text='The company this action affected, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
