# Generated by Django 6.0.7 on 2026-07-24 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0006_activityequipmentrequirement_and_more'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BOQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('import_excel', 'Excel import'), ('import_ai', 'AI import')], default='manual', max_length=20)),
                ('link_mode', models.CharField(choices=[('standalone', 'Standalone — own section structure only'), ('linked_to_wbs', 'Linked to WBS — items can map to Planning')], default='standalone', help_text='UI hint only — whether this BOQ surfaces WBS/Activity linking to the user. Items can hold a wbs/activity FK either way; this just controls whether the picker is shown by default.', max_length=20)),
                ('integration_mode', models.CharField(choices=[('reference', 'Reference only'), ('cost_tracking', 'Cost tracking'), ('full_integration', 'Full integration')], default='reference', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boqs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BOQImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='boq_imports/%Y/%m/')),
                ('import_mode', models.CharField(choices=[('manual_mapping', 'Manual mapping'), ('ai_import', 'AI import')], max_length=20)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', max_length=20)),
                ('boq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_sessions', to='boq.boq')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_import_sessions', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BOQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('boq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='boq.boq')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='boq.boqsection')),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='BOQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('order', models.IntegerField(default=0)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boq_items', to='planning.activity')),
                ('boq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='boq.boq')),
                ('wbs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boq_items', to='planning.wbs')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='boq.boqsection')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boq_items', to='boq.unit')),
            ],
            options={
                'ordering': ['order', 'item_code'],
            },
        ),
        migrations.CreateModel(
            name='BOQRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_number', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_current', models.BooleanField(default=False)),
                ('boq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='boq.boq')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-revision_number'],
                'unique_together': {('boq', 'revision_number')},
            },
        ),
    ]
