# Generated by Django 6.0.7 on 2026-07-26 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0002_seed_units'),
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boqitem',
            name='budget_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boq_items', to='budget.budgetline'),
        ),
    ]
