# Generated by Django 6.0.7 on 2026-07-28 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0004_importsession_health_fields'),
        ('documents', '0002_alter_document_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='boq',
            name='reference_document',
            field=models.ForeignKey(blank=True, help_text='Set only when this BOQ was created via "Reference Only" upload — the actual stored file this BOQ represents. BOQDetailPage renders this file in-app instead of a sections/items editor when set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_boqs', to='documents.document'),
        ),
    ]
