# Generated by Django 6.0.7 on 2026-08-16 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0006_boqitemflag'),
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boq',
            name='tender',
            field=models.ForeignKey(blank=True, help_text='Set when this BOQ belongs to a tender, not yet a won project. Exactly one of project/tender should be set at any time.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boqs', to='tenders.tender'),
        ),
    ]
