# Generated by Django 6.0.7 on 2026-08-16 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0007_boq_tender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boq',
            name='tender',
        ),
    ]
