# Generated by Django 6.0.7 on 2026-07-20 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_company_procurement_approval_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('supplier_type', models.CharField(choices=[('materials', 'Materials Supplier'), ('equipment', 'Equipment Supplier'), ('services', 'Services Provider'), ('subcontractor', 'Subcontractor'), ('other', 'Other')], default='materials', max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('tax_pin', models.CharField(blank=True, help_text='KRA PIN or equivalent tax ID.', max_length=50)),
                ('payment_terms', models.CharField(blank=True, help_text='e.g. "Net 30", "Cash on delivery".', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
