# Generated by Django 6.0.7 on 2026-07-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_company_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('company_admin', 'Company Admin'), ('director', 'Director'), ('operations_manager', 'Operations Manager'), ('finance_manager', 'Finance Manager'), ('accountant', 'Accountant'), ('procurement_manager', 'Procurement Manager'), ('main_store_manager', 'Main Store Manager'), ('hr_manager', 'HR Manager'), ('project_manager', 'Project Manager'), ('site_manager', 'Site Manager'), ('site_engineer', 'Site Engineer'), ('foreman', 'Foreman'), ('qs', 'Quantity Surveyor'), ('storekeeper', 'Site Storekeeper'), ('procurement', 'Procurement Officer'), ('safety_officer', 'Safety Officer'), ('qa_qc_engineer', 'QA/QC Engineer'), ('plant_equipment_officer', 'Plant & Equipment Officer'), ('document_controller', 'Document Controller'), ('management', 'Management'), ('site_supervisor', 'Site Supervisor'), ('subcontractor', 'Subcontractor'), ('client', 'Client'), ('employee', 'Employee')], max_length=30),
        ),
    ]
