# Generated by Django 6.0.7 on 2026-07-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='procurement_approval_threshold',
            field=models.DecimalField(decimal_places=2, default=100000, help_text='Purchase requests at or above this amount require Director approval, in addition to Procurement Manager approval.', max_digits=15),
        ),
    ]
