# Generated by Django 6.0.7 on 2026-08-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('contract', 'Contract'), ('drawing', 'Drawing'), ('boq', 'BOQ'), ('tender', 'Tender'), ('programme', 'Programme'), ('report', 'Report'), ('legal', 'Legal'), ('policy', 'Policy'), ('template', 'Template'), ('photo', 'Photo'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
