# Generated by Django 6.0.7 on 2026-07-26 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterimPaymentCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_number', models.PositiveIntegerField(help_text='Sequential per project — IPC No.1, No.2, ...')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('work_done_amount', models.DecimalField(decimal_places=2, help_text='Cumulative gross value of work completed to date, before retention.', max_digits=18)),
                ('retention_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=16, max_digits=5)),
                ('advance_recovery_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('previous_gross_certified', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('retention_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('amount_after_retention', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_payable', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipcs', to='budget.budget')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipcs', to='projects.project')),
            ],
            options={
                'ordering': ['-certificate_number'],
                'unique_together': {('project', 'certificate_number')},
            },
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(help_text='Sequential per project — VO-1, VO-2, ...')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('cost_impact', models.DecimalField(decimal_places=2, default=0, help_text='Positive = addition to contract sum, negative = omission.', max_digits=18)),
                ('time_impact_days', models.IntegerField(default=0, help_text='Positive = extension, negative = acceleration.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('budget_line', models.ForeignKey(blank=True, help_text='Which budget line this variation adjusts. Leave blank for a purely informational variation not tied to a specific line yet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variations', to='budget.budgetline')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_variations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='projects.project')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_variations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-number'],
                'unique_together': {('project', 'number')},
            },
        ),
    ]
