# Generated by Django 6.0.7 on 2026-08-17 07:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
        ('planning', '0014_delete_activityrequirement'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('period_type', models.CharField(choices=[('week', 'Weekly'), ('month', 'Monthly'), ('year', 'Yearly')], default='month', max_length=10)),
                ('is_current', models.BooleanField(default=True, help_text='Only one current plan per project at a time — mirrors ProjectBaseline.is_current.')),
                ('budget', models.ForeignKey(blank=True, help_text='Optional — the Budget this cash flow is being reconciled against. Null if the project has no budget yet or cash flow is being built standalone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashflow_plans', to='budget.budget')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflow_plans', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashFlowEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('materials', 'Materials'), ('labour', 'Labour'), ('plant', 'Plant & Equipment'), ('subcontract', 'Subcontract'), ('other', 'Other / Unspecified')], default='other', max_length=20)),
                ('entry_type', models.CharField(choices=[('planned', 'Planned'), ('actual', 'Actual')], default='planned', max_length=10)),
                ('period_start', models.DateField(help_text='Normalized to the first day of its week/month/year bucket.')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('derived', 'Derived from BOQ/Budget')], default='manual', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflow_entries', to='planning.activity')),
                ('budget_line', models.ForeignKey(blank=True, help_text='Optional — which Budget line this entry is time-phasing, for reconciliation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashflow_entries', to='budget.budgetline')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='cashflow.cashflowplan')),
            ],
            options={
                'ordering': ['activity_id', 'period_start'],
                'unique_together': {('plan', 'activity', 'category', 'entry_type', 'period_start')},
            },
        ),
    ]
