# Generated by Django 6.0.7 on 2026-08-16 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_company_procurement_approval_threshold'),
        ('documents', '0003_alter_document_category'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('client_name', models.CharField(blank=True, help_text='Free text — the tendering client/consultant. Not apps.clients.Client necessarily, since many tenders come from a consultant, not the end client.', max_length=255)),
                ('mode', models.CharField(choices=[('reference', 'Reference only — document on file'), ('active', 'Active — being priced')], default='reference', max_length=10)),
                ('status', models.CharField(choices=[('filed', 'Filed (reference only)'), ('opportunity', 'Opportunity'), ('pricing', 'Pricing'), ('submitted', 'Submitted'), ('won', 'Won'), ('lost', 'Lost'), ('withdrawn', 'Withdrawn')], default='filed', max_length=20)),
                ('closing_date', models.DateField(blank=True, help_text='Submission deadline. Optional for reference-only tenders.', null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, help_text='Rough value at opportunity stage, before real pricing exists.', max_digits=16, null=True)),
                ('overheads_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('risk_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('profit_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('submitted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('outcome_decided_at', models.DateTimeField(blank=True, null=True)),
                ('loss_reason', models.CharField(blank=True, choices=[('price', 'Price too high'), ('technical', 'Technical score'), ('late', 'Late submission'), ('disqualified', 'Failed qualification'), ('cancelled', 'Client cancelled'), ('other', 'Other / unknown')], max_length=20)),
                ('loss_notes', models.TextField(blank=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_qs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tenders', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
                ('converted_project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_tender', to='projects.project')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reference_document', models.ForeignKey(blank=True, help_text='Set only when mode="reference" — the filed tender document. Same pattern as BOQ.reference_document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_tenders', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderBOQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tenders.tenderboqsection')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_sections', to='tenders.tender')),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TenderBOQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('order', models.IntegerField(default=0)),
                ('material_cost', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('labour_cost', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('plant_cost', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('subcontractor_cost', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('rate_source', models.CharField(choices=[('manual', 'Entered manually'), ('historical', 'From historical rate'), ('procurement_quote', 'From a procurement quotation'), ('rate_library', 'From the Rate Library')], default='manual', max_length=20)),
                ('rate_source_note', models.CharField(blank=True, max_length=255)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_items', to='tenders.tender')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='tenders.tenderboqsection')),
            ],
            options={
                'ordering': ['order', 'item_code'],
            },
        ),
    ]
