# Generated by Django 6.0.7 on 2026-08-16 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderBOQImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='tender_boq_imports/%Y/%m/')),
                ('import_mode', models.CharField(choices=[('manual_mapping', 'Manual mapping'), ('ai_import', 'AI import')], max_length=20)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', max_length=20)),
                ('row_count', models.PositiveIntegerField(blank=True, help_text='Rows successfully imported.', null=True)),
                ('error_count', models.PositiveIntegerField(blank=True, help_text='Rows skipped due to validation errors.', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_sessions', to='tenders.tender')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
