# Generated by Django 6.0.7 on 2026-07-20 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_wbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='wbs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='planning.wbs'),
        ),
    ]
