# Generated by Django 6.0.7 on 2026-07-21 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_activity_wbs'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BaselineActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('planned_start', models.DateField()),
                ('planned_end', models.DateField()),
                ('status_at_snapshot', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('delayed', 'Delayed'), ('completed', 'Completed')], max_length=20)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline_snapshots', to='planning.activity')),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_activities', to='planning.projectbaseline')),
            ],
            options={
                'ordering': ['planned_start'],
            },
        ),
    ]
