# Generated by Django 6.0.7 on 2026-07-21 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_projectbaseline_baselineactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='code',
            field=models.CharField(blank=True, help_text='e.g. A1010', max_length=30),
        ),
        migrations.AddField(
            model_name='activity',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
