# Generated by Django 6.0.7 on 2026-07-23 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('planning', '0005_activity_code_activity_responsible'),
        ('procurement', '0002_purchaserequest_tier3_approver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEquipmentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment_name', models.CharField(help_text='e.g. Poker Vibrator, Concrete Mixer.', max_length=150)),
                ('quantity_required', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_requirements', to='planning.activity')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLabourRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(help_text='e.g. Mason, Carpenter, Steel Fixer.', max_length=100)),
                ('quantity_required', models.PositiveIntegerField(help_text='Number of people needed.')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_requirements', to='planning.activity')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ActivityMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_required', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('requested', 'Requested'), ('fulfilled', 'Fulfilled')], default='pending', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='planning.activity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_requirements', to='inventory.stockitem')),
                ('purchase_request', models.ForeignKey(blank=True, help_text='Set once this material has been rolled into a Purchase Request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_activity_materials', to='procurement.purchaserequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
