# Generated by Django 6.0.7 on 2026-08-01 20:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_activityequipmentrequirement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressupdate',
            options={'ordering': ['-progress_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='progressupdate',
            name='progress_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='The day this progress reflects — may differ from created_at if backfilled.'),
        ),
    ]
