# Generated by Django 6.0.7 on 2026-08-04 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_pendingstockitemrequest'),
        ('planning', '0008_activity_deleted_at_activity_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitymaterial',
            name='pending_request',
            field=models.ForeignKey(blank=True, help_text='Set when this material was requested before the catalog item existed. Cleared (item gets populated instead) once Main Store Manager approves it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_materials', to='inventory.pendingstockitemrequest'),
        ),
        migrations.AlterField(
            model_name='activitymaterial',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_requirements', to='inventory.stockitem'),
        ),
    ]
