# Generated by Django 6.0.7 on 2026-08-12 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_category'),
        ('planning', '0009_activitymaterial_pending_request_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='assigned_planner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_to_plan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='changes_requested_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='planning_status',
            field=models.CharField(choices=[('not_planned', 'Not Planned'), ('in_progress', 'Planning In Progress'), ('submitted', 'Submitted for Approval'), ('approved', 'Approved for Execution'), ('changes_requested', 'Changes Requested')], default='not_planned', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='planning_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='pm_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='pm_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='qs_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='qs_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='qs_budget_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="QS-confirmed budget for this activity's planned resources.", max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='ActivityRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boq_item_code', models.CharField(blank=True, max_length=50)),
                ('boq_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('boq_unit', models.CharField(blank=True, max_length=30)),
                ('planned_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('work_area', models.CharField(blank=True, max_length=255)),
                ('specification', models.CharField(blank=True, max_length=255)),
                ('method_statement_ref', models.CharField(blank=True, max_length=100)),
                ('special_instructions', models.TextField(blank=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirement', to='planning.activity')),
                ('drawing', models.ForeignKey(blank=True, help_text='The governing drawing for this activity, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
