# /app/backend/apps/planning/migrations/0011_activity
# Generated by Django 6.0.7 on 2026-08-13 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_activity_assigned_planner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityequipmentrequirement',
            name='required_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityequipmentrequirement',
            name='required_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityequipmentrequirement',
            name='review_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='activityequipmentrequirement',
            name='revision_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='activitylabourrequirement',
            name='review_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='activitylabourrequirement',
            name='revision_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='activitymaterial',
            name='review_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='activitymaterial',
            name='revision_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ActivityEquipmentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_number', models.PositiveIntegerField()),
                ('quantity_required', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status_at_time', models.CharField(max_length=20)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='planning.activityequipmentrequirement')),
            ],
            options={
                'ordering': ['-revision_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityLabourRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_number', models.PositiveIntegerField()),
                ('quantity_required', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status_at_time', models.CharField(max_length=20)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='planning.activitylabourrequirement')),
            ],
            options={
                'ordering': ['-revision_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityMaterialRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_number', models.PositiveIntegerField()),
                ('quantity_required', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status_at_time', models.CharField(max_length=20)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='planning.activitymaterial')),
            ],
            options={
                'ordering': ['-revision_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityPPERequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_required', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('revision_number', models.PositiveIntegerField(default=1)),
                ('ppe_name', models.CharField(help_text='e.g. Helmet, Safety Boots, Harness.', max_length=150)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppe_requirements', to='planning.activity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityPPERevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_number', models.PositiveIntegerField()),
                ('quantity_required', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status_at_time', models.CharField(max_length=20)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='planning.activitypperequirement')),
            ],
            options={
                'ordering': ['-revision_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityServiceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_required', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('revision_number', models.PositiveIntegerField(default=1)),
                ('service_name', models.CharField(help_text='e.g. Concrete Pumping, Scaffolding, Soil Testing.', max_length=150)),
                ('provider_notes', models.CharField(blank=True, max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requirements', to='planning.activity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityServiceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_number', models.PositiveIntegerField()),
                ('quantity_required', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status_at_time', models.CharField(max_length=20)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='planning.activityservicerequirement')),
            ],
            options={
                'ordering': ['-revision_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityToolRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_required', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('revision_number', models.PositiveIntegerField(default=1)),
                ('tool_name', models.CharField(help_text='e.g. Wheelbarrow, Shovel, Angle Grinder.', max_length=150)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_requirements', to='planning.activity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityToolRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_number', models.PositiveIntegerField()),
                ('quantity_required', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status_at_time', models.CharField(max_length=20)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='planning.activitytoolrequirement')),
            ],
            options={
                'ordering': ['-revision_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequirementGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_type', models.CharField(choices=[('materials', 'Materials'), ('labour', 'Labour'), ('plant_equipment', 'Plant & Equipment'), ('tools', 'Tools'), ('ppe_safety', 'PPE & Safety'), ('services', 'Services / Subcontracting')], max_length=30)),
                ('status', models.CharField(choices=[('not_required', 'Not Required'), ('pending_assignment', 'Pending Assignment'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved')], default='pending_assignment', max_length=25)),
                ('required_on_site', models.DateField(blank=True, help_text='When this resource must physically be available on site.', null=True)),
                ('procurement_deadline', models.DateField(blank=True, help_text='Latest date Procurement must act by to hit required_on_site.', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_groups', to='planning.activity')),
                ('responsible', models.ForeignKey(blank=True, help_text="Who is responsible for preparing this group's requirements.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_groups_owned', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['activity_id', 'group_type'],
                'unique_together': {('activity', 'group_type')},
            },
        ),
        migrations.AddField(
            model_name='activitytoolrequirement',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_items', to='planning.requirementgroup'),
        ),
        migrations.AddField(
            model_name='activityservicerequirement',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='planning.requirementgroup'),
        ),
        migrations.AddField(
            model_name='activitypperequirement',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppe_items', to='planning.requirementgroup'),
        ),
        migrations.AddField(
            model_name='activityequipmentrequirement',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to='planning.requirementgroup'),
        ),
        migrations.AddField(
            model_name='activitylabourrequirement',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labour_items', to='planning.requirementgroup'),
        ),
        migrations.AddField(
            model_name='activitymaterial',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='planning.requirementgroup'),
        ),
    ]
