# Generated by Django 6.0.7 on 2026-08-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_backfill_requirement_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementgroup',
            name='alert_days_before',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Days before required_on_site to alert the project storekeeper. Defaults to 2 if not set.', null=True),
        ),
        migrations.AddField(
            model_name='requirementgroup',
            name='alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
