# Generated by Django 6.0.7 on 2026-08-14 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0013_requirementgroup_alert_days_before_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityRequirement',
        ),
    ]
